# Generated by Django 2.2.5 on 2021-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('writing_date', models.DateField(auto_now_add=True)),
                ('movie_title', models.CharField(max_length=128)),
                ('diary_text', models.TextField()),
                ('photo', models.CharField(max_length=128, null=True)),
                ('mood', models.IntegerField()),
            ],
            options={
                'db_table': 'diaries',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=128)),
                ('pick_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
