# Generated by Django 2.2.5 on 2021-12-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logvie_app', '0002_auto_20211201_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='writing_date',
            field=models.DateField(),
        ),
    ]
