# Generated by Django 2.2.5 on 2021-12-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logvie_app', '0004_auto_20211201_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo',
            field=models.CharField(default='logo_eng.png', max_length=128),
            preserve_default=False,
        ),
    ]
